apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: oggl4m54s-python 
  janus-idp.io/tekton: oggl4m54s-python
  backstage.io/kubernetes-id: oggl4m54s-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: oggl4m54s-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml